
name: Publish Docs

on:
  push:
    tags:
      - '**'

jobs:
  update-docs:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive' # for doxygen-awesome-css
      - 
        name: install doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      - 
        name: set version
        run: |
          _version_tag=$(git describe --tags)
          _cmake_version=v$(grep "^[ \t]*VERSION" CMakeLists.txt | sed 's/[^.0-9]*//g')
          if [[ "${_version_tag}" != "${_cmake_version}" ]]; then
            echo "::error::Git version ${_version_tag} does not match CMake version ${_cmake_version}"
            exit 1
          fi
          echo ${_version_tag}
          echo "PROJECT_NUMBER = ${_version_tag}" >> docs/doxyfile
      - 
        name: run doxygen
        run: doxygen docs/doxyfile
      - 
        name: publish generated content
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.TOKEN }}
