
name: Test

on:
  push:
    branches:
      - '**' #main
    tags:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ldmx/dev:latest
    steps:
      -
        name: checkout source
        uses: actions/checkout@v4
      -
        name: test compile
        run: |
          cmake -B build -S . 
          cmake --build build
