
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boost: [1.80.0]
        geant4: [11.0.3]
    env:
      INSTALL_PREFIX: ${{github.workspace}}/deps
    steps:
      -
        name: cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{env.INSTALL_PREFIX}}
          key: boost-${{matrix.boost}}-geant4-${{matrix.geant4}}
      -
        name: install boost
        if: ${{ steps.cache-deps.outputs.catch-hit != 'true' }}
        run: |
          mkdir src
          boost_version=${{matrix.boost}}
          wget -q -O - https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz |\
            tar -xz --strip-components=1 --directory src
          cd src
          ./bootstrap.sh
          ./b2 install --prefix=${INSTALL_PREFIX}
          cd ..
          rm -rf src
      -
        name: install geant4
        if: ${{ steps.cache-deps.outputs.catch-hit != 'true' }}
        run: |
          mkdir src
          wget -q -O - https://github.com/geant4/geant4/archive/refs/tags/v${{matrix.geant4}}.tar.gz |\
            tar -xz --strip-components=1 --directory src
          cmake \
            -DGEANT4_INSTALL_DATA=ON \
            -DGEANT4_INSTALL_EXAMPLES=OFF \
            -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
            -B src/build \
            -S src
          cmake --build src/build --target install
          rm -rf src 
      -
        name: checkout source
        uses: actions/checkout@v3
      -
        name: test compile
        run: |
          source ~/deps/bin/geant4.sh
          cmake -B build -S . 
          cmake --build build

